#pragma define raw  on
#pragma fixed       on
#pragma block_scope on

#include "zcommon.acs"
#library "ACS_PDA"     // [marrub] This should be after zcommon.acs. (Don't ask me why.)

#include "../headers/PDA_LIB.ach" // Stores IDs, arrays and other things the PDA uses.
#include "../database/equipment.idb" // Armors, boots, and etc.
#include "../headers/PDA_FNC.ach"

#include "ACS_INP.acs"

global str 43:weaponval;
global str 44:armorval;



function void DebugIDs (void) {
    log("PDA_CURSORID=%d:",PDA_CURSORID);
    log("PDA_PLAYERS_BUTTON=%d:",PDA_PLAYERS_BUTTON);
    log("PDA_WEAPONS_BUTTON=%d:",PDA_WEAPONS_BUTTON);
    log("PDA_EQUIPMENT_BUTTON=%d:",PDA_EQUIPMENT_BUTTON);
    log("PDA_ASSEMBLIES_BUTTON=%d:",PDA_ASSEMBLIES_BUTTON);
    log("PDA_ITEMS_BUTTON=%d:",PDA_ITEMS_BUTTON);
    log("PDA_BESTIARY_BUTTON=%d:",PDA_BESTIARY_BUTTON);
    log("PDA_MISC_BUTTON=%d:",PDA_MISC_BUTTON);
    log("PDA_HELP_BUTTON=%d:",PDA_HELP_BUTTON);
    log("PDA_WINFO_BUTTON=%d:",PDA_WINFO_BUTTON);
    log("PDA_BEAST_UV=%d:",PDA_BEAST_UV);
    log("PDA_BEAST_NM=%d:",PDA_BEAST_NM);
    log("PDA_BEAST_TP=%d:",PDA_BEAST_TP);
    log("PDA_BEAST_AG=%d:",PDA_BEAST_AG);
    log("PDA_BEAST_EX=%d:",PDA_BEAST_EX);
    log("PDA_PREV_PAGE=%d:",PDA_PREV_PAGE);
    log("PDA_NEXT_PAGE=%d:",PDA_NEXT_PAGE);
    log("PDA_MODS_PAGE=%d:",PDA_MODS_PAGE);
    log("PDA_ARTIFACTS_PAGE=%d:",PDA_ARTIFACTS_PAGE);
    log("PDA_CAT_DESCRIPTION=%d:",PDA_CAT_DESCRIPTION);
    log("PDA_PLAYER_BODY_ICON=%d:",PDA_PLAYER_BODY_ICON);
    log("PDA_PLAYER_ARMOR_ICON=%d:",PDA_PLAYER_ARMOR_ICON);
    log("PDA_PLAYER_BACKPACK_ICON=%d:",PDA_PLAYER_BACKPACK_ICON);
    log("PDA_PLAYER_BOOTS_ICON=%d:",PDA_PLAYER_BOOTS_ICON);
    log("PDA_ASSEMBLY_ID_END=%d:",PDA_ASSEMBLY_ID_END);
    log("PDA_BEASTS_ID_END=%d:",PDA_BEASTS_ID_END);
    log("PDA_WORN_EQUIPMENT=%d:",PDA_WORN_EQUIPMENT);
    log("PDA_STASHEDEQUIPMENT=%d:",PDA_STASHEDEQUIPMENT);
    log("PDA_NOEQID=%d:",PDA_NOEQID);
    log("PDA_MODIDRANGE=%d:",PDA_MODIDRANGE);
    log("PDA_INFO4ID=%d:",PDA_INFO4ID);
    log("PDA_INFO3ID=%d:",PDA_INFO3ID);
    log("PDA_INFO2ID=%d:",PDA_INFO2ID);
    log("PDA_INFOID=%d:",PDA_INFOID);
    log("PDA_SCROLLDNID=%d:",PDA_SCROLLDNID);
    log("PDA_SCROLLUPID=%d:",PDA_SCROLLUPID);
    log("PDA_ITEMS_END=%d:",PDA_ITEMS_END);
    log("PDA_LASTID=%d:",PDA_LASTID);
    log("PDA_PONG_LEFTPADDLE=%d:",PDA_PONG_LEFTPADDLE);
    log("PDA_PONG_RIGHTPADDLE=%d:",PDA_PONG_RIGHTPADDLE);
    log("PDA_PONG_BALL=%d:",PDA_PONG_BALL);
    log("PDA_PONG_TOPBORD=%d:",PDA_PONG_TOPBORD);
    log("PDA_PONG_BOTBORD=%d:",PDA_PONG_BOTBORD);
    log("PDA_PONG_PLAYERSCORE=%d:",PDA_PONG_PLAYERSCORE);
    log("PDA_PONG_AISCORE=%d:",PDA_PONG_AISCORE);
    log("PDA_INFOTOPID=%d:",PDA_INFOTOPID);
    log("PDA_TAB_BUTTONS_START=%d:",PDA_TAB_BUTTONS_START);
    log("PDA_TAB_BUTTONS_END=%d:",PDA_TAB_BUTTONS_END);
    log("PDA_ID=%d:",PDA_ID);
    log("PDA_REALLYLASTID=%d:",PDA_REALLYLASTID);
    log("PDA_EQUIPMENTINVIDRANGE=%d:",PDA_EQUIPMENTINVIDRANGE);
    log("PDA_EQUIPMENTWORNIDRANGE=%d:",PDA_EQUIPMENTWORNIDRANGE);
    log("PDA_TOOLTIPGFX=%d:",PDA_TOOLTIPGFX);
    log("PDA_TOOLTIPID=%d:",PDA_TOOLTIPID);
    log("PDA_WEAPON_ICON=%d:",PDA_WEAPON_ICON);
    log("PDA_PLYR_ICON=%d:",PDA_PLYR_ICON);
}

// [marrub] This is a pretty cool hack
script "PDA_CheckPlayer1Inventory" (str name) {
   SetActivator(0, AAPTR_PLAYER1);
   SetResultValue(CheckInventory(name));
}

script "PDA_GiveEveryoneInventory" (str name) {
   SetActivator(0, AAPTR_NULL);
   GiveInventory(name, 1);
   SetResultValue(1);
}

script "PDA_SetEveryoneInventory" (str name) {
   SetActivator(0, AAPTR_NULL);
   SetInventory(name, 1);
   SetResultValue(1);
}

script "DRLA_HUD_InfoHandler" ENTER {
    while (true) {
        weapon_checks[weapon_checks_isdemonic] = CheckInventory("RLDemonicWeaponToken");
        
        player_weapon[player_weapon_current] = GetWeapon();
        player_weapon[player_weapon_trimmed] = StrTrim(player_weapon[player_weapon_current], 2, 0);

        weapon_info[weapon_info_icon]     = StrParam("PDA_WEAPON_%s:_ICON", player_weapon[player_weapon_trimmed]);
        weapon_info[weapon_info_name]     = StrParam("PDA_WEAPON_%s:_NAME", player_weapon[player_weapon_trimmed]);
        weapon_info[weapon_info_dualname] = StrParam("PDA_WEAPON_%s:DEMONARTIFACTS_NAME", player_weapon[player_weapon_trimmed]);

        Weapon_Mod_Quantity[mod_bulk]      = CheckInventory(StrParam("%s:BulkMod", player_weapon[player_weapon_current])),
        Weapon_Mod_Quantity[mod_power]     = CheckInventory(StrParam("%s:PowerMod", player_weapon[player_weapon_current])),
        Weapon_Mod_Quantity[mod_agility]   = CheckInventory(StrParam("%s:AgilityMod", player_weapon[player_weapon_current])),
        Weapon_Mod_Quantity[mod_technical] = CheckInventory(StrParam("%s:TechnicalMod", player_weapon[player_weapon_current])),
        Weapon_Mod_Quantity[mod_sniper]    = CheckInventory(StrParam("%s:SniperMod", player_weapon[player_weapon_current])),
        Weapon_Mod_Quantity[mod_firestorm] = CheckInventory(StrParam("%s:FirestormMod", player_weapon[player_weapon_current])),
        Weapon_Mod_Quantity[mod_nano]      = CheckInventory(StrParam("%s:NanoMod", player_weapon[player_weapon_current])),
        Weapon_Mod_Quantity[mod_artifact]  = CheckInventory(StrParam("%s:DemonArtifacts", player_weapon[player_weapon_current]));
        
        str weaponName = (weapon_checks[weapon_checks_isdemonic]) 
                        ? (CheckInventory(StrParam("%s:DemonArtifacts", player_weapon[player_weapon_current])) 
                            ? weapon_info[weapon_info_dualname] 
                            : weapon_info[weapon_info_name]) 
                        : weapon_info[weapon_info_name];
        str modsOn     = StrParam("%l: ", weaponName);

        // Weapons
        if (Weapon_Mod_Quantity[mod_power] || Weapon_Mod_Quantity[mod_bulk] || Weapon_Mod_Quantity[mod_agility] || Weapon_Mod_Quantity[mod_technical] || 
        Weapon_Mod_Quantity[mod_sniper] || Weapon_Mod_Quantity[mod_firestorm] || Weapon_Mod_Quantity[mod_nano] || Weapon_Mod_Quantity[mod_artifact] )
        {
            modsOn = StrParam("%l: (", weaponName);
            modsOn = (Weapon_Mod_Quantity[mod_power]     > 0) ? StrParam("%s:P%i:\n", modsOn, Weapon_Mod_Quantity[mod_power]    ) : StrParam("%s:\n", modsOn);
            modsOn = (Weapon_Mod_Quantity[mod_bulk]      > 0) ? StrParam("%s:B%i:\n", modsOn, Weapon_Mod_Quantity[mod_bulk]     ) : StrParam("%s:\n", modsOn);
            modsOn = (Weapon_Mod_Quantity[mod_agility]   > 0) ? StrParam("%s:A%i:\n", modsOn, Weapon_Mod_Quantity[mod_agility]  ) : StrParam("%s:\n", modsOn);
            modsOn = (Weapon_Mod_Quantity[mod_technical] > 0) ? StrParam("%s:T%i:\n", modsOn, Weapon_Mod_Quantity[mod_technical]) : StrParam("%s:\n", modsOn);
            modsOn = (Weapon_Mod_Quantity[mod_sniper]    > 0) ? StrParam("%s:S%i:\n", modsOn, Weapon_Mod_Quantity[mod_sniper]   ) : StrParam("%s:\n", modsOn);
            modsOn = (Weapon_Mod_Quantity[mod_firestorm] > 0) ? StrParam("%s:F%i:\n", modsOn, Weapon_Mod_Quantity[mod_firestorm]) : StrParam("%s:\n", modsOn);
            modsOn = (Weapon_Mod_Quantity[mod_nano]      > 0) ? StrParam("%s:N%i:\n", modsOn, Weapon_Mod_Quantity[mod_nano]     ) : StrParam("%s:\n", modsOn);
            modsOn = (Weapon_Mod_Quantity[mod_artifact]  > 0) ? StrParam("%s:D%i:\n", modsOn, Weapon_Mod_Quantity[mod_artifact] ) : StrParam("%s:\n", modsOn);
            modsOn = StrParam("%s:)\n", modsOn);
        } else if (!Weapon_Mod_Quantity[mod_power] && !Weapon_Mod_Quantity[mod_bulk] && !Weapon_Mod_Quantity[mod_agility] && !Weapon_Mod_Quantity[mod_technical] && !Weapon_Mod_Quantity[mod_sniper] && !Weapon_Mod_Quantity[mod_firestorm] && !Weapon_Mod_Quantity[mod_nano] && !Weapon_Mod_Quantity[mod_artifact]) {
            modsOn = StrParam("%l:", weaponName);
        }
        weaponval = modsOn;

        weapon_checks[weapon_checks_disassemblable] = (GetActorClass(0) == "DoomRLTechnician" && !CheckInventory("RLStandardWeaponToken"));
        weapon_checks[weapon_checks_supports_artifacts] = CheckInventory(StrParam("%s:DemonArtifacts", player_weapon[player_weapon_current]));

        setMaxModLimit();

        checkPlayerWeaponPerk();
        checkWeaponArmorSetPerk();

        // Armor
        str armorType = GetArmorInfo(ARMORINFO_CLASSNAME);
        if (armorType != "None") {
            armorType = StrMid(armorType, 2, StrLen(armorType) - (CheckActorClass(0,"DoomRLRenegade") ? 10 : 0));
            armorType = StrParam(s:"PDA_ARMOR_", s:armorType, s:"_FLATNAME");
            armorval  = StrParam(l:armorType, s:" (",i:CheckInventory("BasicArmor"),s:"%)");
        } else {
            armorval = StrParam(s:"none");
        }
        Delay(1);
    }
}


script "DRLA_HUDStyleChanger" (void) {
    #define statusbarMax 6
    str statusbarHuds[statusbarMax] = {
        "RLStatusBarTritiumHUDType",
        "RLStatusBarTritiumHUDType",
        "RLStatusBarGeoscaperHUDType",
        "RLStatusBarRepublicHUDType",
        "RLStatusBarRigelatinHUDType",
        "RLStatusBarVintageHUDType"
    };
    #define fullscreenMax 6
    str fullscreenHuds[fullscreenMax] = {
        "RLFullscreenShockHUDType", 
        "RLFullscreenHazardHUDType", 
        "RLFullscreenCorruptHUDType", 
        "RLFullscreenFluidHUDType",
        "RLFullscreenStatyHUDType",
        "RLFullscreenTrackerHUDType"
    };

    int statusbarStyleCVar  = GetCVar("DRLA_HUD_statusbarstyle");
    int fullscreenStyleCVar = GetCVar("DRLA_HUD_fullscreenstyle");

    for (int s = 0; s <  statusbarMax; s++) TakeActorInventory(PlayerNumber(),  statusbarHuds[s], 1);
    for (int f = 0; f < fullscreenMax; f++) TakeActorInventory(PlayerNumber(), fullscreenHuds[f], 1);

    GiveActorInventory(PlayerNumber(),  statusbarHuds[statusbarStyleCVar] , 1);
    GiveActorInventory(PlayerNumber(), fullscreenHuds[fullscreenStyleCVar], 1);
}

/** TODO: This and the below script are redundant, look into it */
function void doPDASync (void) {
    for (int page = 0; page < DRLA_DIFFICULTYTIERS; page++) {
        for (int m = 0; m < DRLA_MONSTER_PAGE_MAX; m++) {
            localListEnemy[list_kill_count] = StrParam("%s:KillCounter", DRLA_Bestiary[page][m][beast_TOKEN]);
            monsterCheck[page][m]  = CheckInventory(localListEnemy[list_kill_count]);

            if (CheckPointerInventory(localListEnemy[list_kill_count], PlayerNumber()) > 0) {
                PDA_SetEveryoneInventory(localListEnemy[list_kill_count]);
            }
        }
    }

    setAssemblyData();

    str actorToken = "";
    for (int ti = 0; ti <= master_max; ti++) {
        if (ti % 2 == 0) 
            actorToken = stringArray[ASSEMBLY_DIM][ti];

        if (CheckInventory(actorToken)) 
            PDA_SetEveryoneInventory(actorToken);
    }
}

SCRIPT "HeyADollar" enter {
    doPDASync();
    GiveInventory("RLHUDStyleChanger", 1);
    ACS_NamedExecuteAlways("DRLA_HUDStyleChanger", 0);
}

function void setPDADefaults (int playerNum) {
    PDA_Info[playerNum].active = false;
    PDA_Info[playerNum].pongRunning = false;
    PDA_Info[playerNum].armorHax = false;

    PDA_Info[playerNum].category = 0;
    PDA_Info[playerNum].prevCategory = -1;
    PDA_Info[playerNum].page = 1;
    PDA_Info[playerNum].prevPage = -1;
    PDA_Info[playerNum].pageMax = 0;

    PDA_Info[playerNum].textY = 0;
    PDA_Info[playerNum].maxTextY = -200;
    PDA_Info[playerNum].scrollingY = PDA_SCROLL_TOP;
    PDA_Info[playerNum].scrollYDelta = 0;

    PDA_Info[playerNum].clicked = false;
    PDA_Info[playerNum].newEntry[0] = false;

    PDA_Info[playerNum].assemblyOffset = 0;
    PDA_Info[playerNum].currentAssembly = 0;
    PDA_Info[playerNum].maxAssembliesPer = 255;

    PDA_Info[playerNum].playSoundOnce = false;

    PDA_Info[playerNum].maxModLimit = 0;
    PDA_Info[playerNum].detailFetch[playerNum] = "null";

    PDA_Info[playerNum].dirty = true;
    PDA_Info[playerNum].scrollDirty = true;
    PDA_Info[playerNum].prevScrollingY = PDA_SCROLL_TOP;

    PDA_Info[playerNum].equipmentLimit = 0;
    PDA_Info[playerNum].equipmentBaseY = 30.0;
    PDA_Info[playerNum].equipmentId = 0;
    PDA_Info[playerNum].stopEquipmentEarly = false;

    PDA_Info[playerNum].clipRegion = "HEADER"; // Always starts here by default
    PDA_Info[playerNum].heading = "PDA_MENU_HEADER";

    for (int b = 0; b < PDA_BUTTON_MAX; b++) {
        PDA_Button[playerNum][b].alpha = DEFAULT_BUTTON_ALPHA;
    }

    /*
    PDA_Mouse[playerNum].x = 0;
    PDA_Mouse[playerNum].y = 0;
    PDA_Mouse[playerNum].m1 = false;
    PDA_Mouse[playerNum].m2 = false;
    PDA_Mouse[playerNum].pollRate = 1;
    */
}

// [marrub] Static init stuff
script "PDA_GSInit" open {
    for (int i = 0; i < MAX_PLAYERS; i++) {
        if (!PlayerInGame(i)) continue;
        setPDADefaults(i);
    }
}

#define PDA_ACTIVATE 1
#define PDA_DEACTIVATE 0
#define PDA_SetGraphicSize() SetHudSize(320,200,0)

function void PDA_SetDisplay(int state) {
    int PDA_THEME = GetUserCVar(PlayerNumber (), "DRLA_PDA_theme");
    str pdaGraphic = "RLZPDA2";

    // This could potentially be wired differently to be more dynamic. Maybe StrParam use here as well, dunno.
    switch (PDA_THEME) {
        case THEME_SLIM:
            pdaGraphic = "RLZPDA3";
            break;
        case THEME_BULKY:
        default:
            pdaGraphic = "RLZPDA2";
            break;
    }

    switch (state) {
        case PDA_ACTIVATE:
            PDA_FONT[lower_font] = GetUserCVarString(PlayerNumber(), "DRLA_PDA_font");
            PDA_FONT[mono_font]  = GetUserCVarString(PlayerNumber(), "DRLA_PDA_monofont");
            PDA_FONT[slim_font]  = GetUserCVarString(PlayerNumber(), "DRLA_PDA_slimfont");
            PDA_HasEquipment();

            if (!localOneEquipFirst) {
                if (localHasArmor) {
                    localEqBoolField = localHasArmor << 0;
                    localOneEquipFirst = true;
                }
                if (localHasBoots) {
                    localEqBoolField = localHasBoots << 1;
                    localOneEquipFirst = true;
                }
                if (localHasBackpack) {
                    localEqBoolField = localHasBackpack << 2;
                    localOneEquipFirst = true;
                }
            }
            else {
                if (!localHasArmor && !localHasBoots && !localHasBackpack) localOneEquipFirst = false;
            }


            PDA_UnsetScrollArrows();

            SetPlayerProperty(0,1,PROP_TOTALLYFROZEN);

            // No more murdering people while browsing your iP- er, PDA!
            GiveInventory("RLSynthFireDisabled",1);

            FadeTo(0, 0, 0, 0.5, 0.0);
            PDA_SetFullDirty();

            PDA_SetGraphicSize();
            DisplayIconAlways(pdaGraphic, PDA_ID, 0.5, 0.5, 0, 1);

            PDA_PlaySound("UI/PDA/Online", "pda/soldieropen", 80);

            ACS_NamedExecuteAlways("PDA_MouseController",0);
            ACS_NamedExecuteAlways("PDA_Core",0);

            PDA_Local.active = true;
            break;
        case PDA_DEACTIVATE:
            PDA_Local.active = false;
            PDA_Local.pongRunning = false;

            PDA_PlaySound("UI/PDA/Offline", "pda/soldierclose", 80);

            PDA_ClearDirty();

            PDA_NOPONG();
            PDA_ClearHeader();
            PDA_UnsetScrollArrows();
            PDA_SuperWipe("PDA_SetDisplay");
            setPDADefaults(PlayerNumber());

            DisplayIconAlways(pdaGraphic, PDA_ID, 0.5, 0.5, 0, 0);

            SetPlayerProperty(0,0,PROP_TOTALLYFROZEN);
            TakeInventory("RLSynthFireDisabled",1);
            FadeTo(0, 0, 0, 0.0, 0.0);

            if (PDA_Local.category == PDA_CREDITS) SetMusic("*");

            break;
    }
    PDA_SetFullDirty();
}

// Display terminal
SCRIPT "PDA_Display" (void) net {
    if (!PDA_Local.active) {
        PDA_SetDisplay(PDA_ACTIVATE);
    } else {
        PDA_SetDisplay(PDA_DEACTIVATE);
    }
}

SCRIPT "PDA_YOUAREDEADnotbigsurprise" DEATH {
    if (PDA_Local.active) {
        PDA_SetDisplay(PDA_DEACTIVATE);
    }
}

/** Attempt to eliminate problems that result from dying w/ PDA*/
SCRIPT "PDA_Respawn" RESPAWN {
    if (PDA_Local.active) {
        PDA_SetDisplay(PDA_DEACTIVATE);
    }
}


function void page_menu (void) {
    if (PDA_Local.category != PDA_MENU) return;
    #include "../../pages/menu.pdap"
}

function void page_player (void) {
    if (PDA_Local.category != PDA_CLASSES) return;
    #include "../../pages/player.pdap"
}

function void page_weapons (void) {
    if (PDA_Local.category != PDA_WEAPONS) return;
    #include "../../pages/weapons.pdap"
}

function void page_armors (void) {
    if (PDA_Local.category != PDA_EQUIPMENT) return;
   #include "../../pages/equipment.pdap"
}

function void page_assemblies (void) {
    if (PDA_Local.category != PDA_ASSEMBLIES) return;
    #include "../../pages/assemblies.pdap"
}

function void page_bestiary (void) {
    if (PDA_Local.category != PDA_BESTIARY) return;
    checkMonsterKillCount();
    updateOldMonsterKillCount();
    #include "../../pages/bestiary.pdap"
}

function void page_items (void) {
    if (PDA_Local.category != PDA_ITEMS) return;
    #include "../../pages/items.pdap"
}

function void page_help (void) {
    if (PDA_Local.category != PDA_HELP) return;
    #include "../../pages/help.pdap"
}

function void page_info (void) {
    if (PDA_Local.category != PDA_WINFO) return;
    #include "../../pages/info.pdap"
}

function void page_misc (void) {
    if (PDA_Local.category != PDA_MISC) return;
    #include "../../pages/misc.pdap"
}

function void page_credits (void) {
    if (PDA_Local.category != PDA_CREDITS) return;
    #include "../../pages/credits.pdap"
}

function void page_monster_info (void) {
    if (PDA_Local.category != PDA_BESTIARY_DETAIL) return;
    checkMonsterKillCount();
    updateOldMonsterKillCount();
    #include "../../pages/beastinfo.pdap"
}

function void page_assembly_info (void) {
    if (PDA_Local.category != PDA_ASSEMBLY_DETAIL) return;
    #include "../../pages/assemblyinfo.pdap"
}

// function void page_pong (void) {
//     if (PDA_Local.category != PDA_PONG) return;
//     #include "../../pages/pong.pdap"
// }

// function void page_equipment_info (void) {
//     if (PDA_Local.category != PDA_EQUIPMENT_DETAIL) return;
//     #include "../../pages/equipmentinfo.pdap"
// }

function void PDA_OnChange (void) {
    afterPageDefaults("PDA_OnChange");
    PDA_ChangeScrolling();
    PDA_SetDataPerPage();

    #include "PDA_STC.acs"

    PDA_SetFullDirty();
    PDA_Local.prevCategory = PDA_Local.category;
    PDA_Local.prevPage = PDA_Local.page;
}

function void UndrawTabs (void) {
    if (PDA_LocalButton[TAB1].type == "tab") PDA_ButtonHandler(TAB1, false, 1, NO_TOOLTIP, B_ONLY_VISUAL, B_CLEAR);
    if (PDA_LocalButton[TAB2].type == "tab") PDA_ButtonHandler(TAB2, false, 1, NO_TOOLTIP, B_ONLY_VISUAL, B_CLEAR);
    if (PDA_LocalButton[TAB3].type == "tab") PDA_ButtonHandler(TAB3, false, 1, NO_TOOLTIP, B_ONLY_VISUAL, B_CLEAR);
    if (PDA_LocalButton[TAB4].type == "tab") PDA_ButtonHandler(TAB4, false, 1, NO_TOOLTIP, B_ONLY_VISUAL, B_CLEAR);
    if (PDA_LocalButton[TAB5].type == "tab") PDA_ButtonHandler(TAB5, false, 1, NO_TOOLTIP, B_ONLY_VISUAL, B_CLEAR);
    PDA_SetupScreenBounds();
}

SCRIPT "PDA_Core" (void) {
    PDA_ResetScroll();

    if (PDA_Local.active) {
        if (GetUserCvar(PlayerNumber(), "DRLA_PDA_firsttime") != FALSE) PDA_SetCategory(PDA_HELP);
        PDA_DefaultFont();

        separator_character = StrParam("%l:", "PDA_SEPARATOR_CHARACTER");
    }

    while (PDA_Local.active) {
        ++PDA_Local.ptic;

        if (PDA_ScrollMoved) {
            PDA_SetFullDirty();
            PDA_ChangeScrolling();
        }
        PDA_HandleHeader();

        if (PDA_CategoryChanged || PDA_PageChanged) {
            PDA_OnChange();
            UndrawTabs();
        }
        // DebugIDs();
        
        switch (PDA_Local.category) {
            case PDA_MENU:
                page_menu();
                break;
            case PDA_CLASSES:
                page_player();
                break;
            case PDA_WEAPONS:
                page_weapons();
                break;
            case PDA_EQUIPMENT:
                page_armors();
                break;
            case PDA_ASSEMBLIES:
                page_assemblies();
                break;
            case PDA_BESTIARY:
                page_bestiary();
                break;
            case PDA_ITEMS:
                page_items();
                break;
            case PDA_HELP:
                page_help();
                break;
            case PDA_MISC:
                page_misc();
                break;
            case PDA_CREDITS:
                page_credits();
                break;
            
            // case PDA_PONG:
            //     page_menu();
            //     break;
            // case PDA_EQUIPMENT_DETAIL:
            //     page_equipment_info();
                //     break;
            case PDA_ASSEMBLY_DETAIL:
                page_assembly_info();
                break;
            case PDA_BESTIARY_DETAIL:
                page_monster_info();
                break;
            default:
                log("how'd you get here?");
                break;
        }
        PDA_Local.prevScrollingY = PDA_Local.scrollingY;
        Delay(PDA_RESPONSIVENESS);

        if (PDA_ScrollableNeedsDraw) {
            PDA_ClearDirty();
        }
        // isDirtyBoy("PDA_Core Loop");
        if (PDA_Local.ptic > 255) PDA_Local.ptic = 0;
    }
    SetHudClipRect(0,0,0,0,0);
}

#include "ACS_WRT.acs"

// EOF
