#define PDA_ChangeDelay 4
#define PDA_ScrollDelay 2
#define HOLD_MAX 15
#define ACTIVATOR -1

#define setScrollDelta() (PDA_Local.scrollingY > PDA_Local.prevScrollingY) ? 1 : (PDA_Local.scrollingY == PDA_Local.prevScrollingY) ? 0 : -1;

#define HMIN (PDA_SCREEN_X)
#define HMAX (PDA_SCREEN_WIDTH  + PDA_SCREEN_X - 7)
#define VMIN (PDA_SCREEN_Y)
#define VMAX (PDA_SCREEN_HEIGHT + PDA_SCREEN_Y - 7)

function void handleClicks (void) {
    if (holdingAction) {
        ++PDA_LocalMouse.mtic;

        PDA_LocalMouse.action   = mouse_click;
        if (PDA_LocalMouse.mtic > HOLD_THRESHOLD) {
            PDA_LocalMouse.action   = mouse_hold;
        }
    }

    if (pressedBack) {
        // if (PDA_LocalMouse.m2) {
        PDA_LocalMouse.state = cursor_default;
        PDA_LocalMouse.action = mouse_back;
        PDA_PlaySound("UI/PDA/Cancel", "pda/soldier", 80);

        PDA_ResetScroll();
    }

    if (!PDA_LocalMouse.m1 && !PDA_LocalMouse.m2) {
        PDA_LocalMouse.action = mouse_none;
        if (PDA_LocalMouse.mtic > 0) PDA_LocalMouse.mtic = 0;
    }
}

function str handleCursorChange (void) {
    /*
     *  Cursor should:
     *      DEFAULT when ???
     *      POINTER when over a clickable object
     *      GRAB    when idle
     *      HOLDER  when dragging screen around
     */
    if (PDA_LocalMouse.state == cursor_default)      return (PDA_LocalMouse.m1) ? "PDACURS" : "PDACUR";
    else if (PDA_LocalMouse.state == cursor_pointer) return "PDAPNT";
    else if (PDA_LocalMouse.state == cursor_grab)    return "PDAGRB";
    else if (PDA_LocalMouse.state == cursor_holding) return "PDAHLD";
}

function void handleScroll (fixed yScale) {
    if (holdingAction) {
        if (PDA_LocalMouse.mtic > HOLD_THRESHOLD) {
            PDA_SetFullDirty();
            PDA_Local.scrollingY   += PDA_LocalMouse.y - PDA_LocalMouse.oldY;
            PDA_Local.scrollYDelta  = setScrollDelta();
        }
    }
    if (PDA_LocalMouse.y < VMIN) {
        if (PDA_Local.scrollingY < PDA_SCREEN_Y) {
            PDA_Local.scrollingY += 2.0 * yScale;
            PDA_Local.scrollYDelta = setScrollDelta();
        }
    }
    if (PDA_LocalMouse.y > VMAX) {
        if (PDA_Local.scrollingY > PDA_Local.maxTextY) {
            PDA_Local.scrollingY -= 2.0 * yScale;
            PDA_Local.scrollYDelta = setScrollDelta();
        }
    }
    if (PDA_Local.scrollingY < PDA_Local.maxTextY) PDA_Local.scrollingY = PDA_Local.maxTextY;
    if (PDA_Local.scrollingY > VMIN)               PDA_Local.scrollingY = VMIN;
}

function void handleMouseMove (bool inverted, fixed xScale, fixed yScale, int xSens, int ySens) {

    fixed playerX = GetPlayerInputFixed(ACTIVATOR, INPUT_YAW)   - (GetPlayerInputFixed(ACTIVATOR, INPUT_SIDEMOVE)    / xSens);
    fixed playerY = GetPlayerInputFixed(ACTIVATOR, INPUT_PITCH) + (GetPlayerInputFixed(ACTIVATOR, INPUT_FORWARDMOVE) / ySens);

    PDA_LocalMouse.x -= (playerX << xSens) * xScale;

    if (inverted) {
        PDA_LocalMouse.y += (playerY << ySens) * yScale;
    } else {
        PDA_LocalMouse.y -= (playerY << ySens) * yScale;
    }

    PDA_LocalMouse.moving = (PDA_LocalMouse.x != PDA_LocalMouse.oldX || PDA_LocalMouse.y != PDA_LocalMouse.oldY);

    if (PDA_LocalMouse.y < VMIN) PDA_LocalMouse.y = VMIN;
    if (PDA_LocalMouse.y > VMAX) PDA_LocalMouse.y = VMAX;

    if (PDA_LocalMouse.x < HMIN) PDA_LocalMouse.x = HMIN;
    if (PDA_LocalMouse.x > HMAX) PDA_LocalMouse.x = HMAX;
}

SCRIPT "PDA_MouseController" (void)
{
    /** Thanks to HeXaGoN for the maths behind the mouse cursor here! */
    const int anymask =
        BT_FORWARD | BT_BACK | BT_ATTACK | BT_ALTATTACK | BT_MOVERIGHT | BT_RIGHT | BT_MOVELEFT | BT_LEFT;
    int buttons[MAX_PLAYERS], oldbuttons[MAX_PLAYERS];
    
    int MIN_HUD_W = 320,
        MIN_HUD_Y = 200;

    bool inverted = false;

    str graphic[MAX_PLAYERS] = {"","","","","","","",""};

    #define localCursor graphic[PlayerNumber()]
    
    fixed xScale, yScale;
          
    if (GameType() == GAME_SINGLE_PLAYER)
        inverted = GetCVar("invertmouse");

    int PDA_X_sensitivity = GetCvar("DRLA_PDA_sensitivity_x"),
        PDA_Y_sensitivity = GetCvar("DRLA_PDA_sensitivity_y");
    
    SetHudSize(MIN_HUD_W, MIN_HUD_Y, 0);

    while (PDA_Local.active)
    {
        #define currButton buttons[PlayerNumber()]
        #define oldButton oldbuttons[PlayerNumber()]
        // bool noPrescale = GetCVar("m_noprescale");

                                 currButton = GetPlayerInput(ACTIVATOR, INPUT_BUTTONS);
        PDA_LocalMouse.oldState = oldButton = GetPlayerInput(ACTIVATOR, INPUT_OLDBUTTONS);
          
        PDA_LocalMouse.oldY = PDA_LocalMouse.y;
        
        PDA_LocalMouse.m1 = (currButton & _ACTION) ? true : false;
        PDA_LocalMouse.m2 = (currButton & _BACK)   ? true : false;

        // kd: I AM REINFORCEMENTS FROM A DIFFERENT DIMENSION
        fixed mouse_sensitivity    = GetOddSensitivityCVarFixed("mouse_sensitivity", 1.0);
        fixed x_sensitivity        = GetOddSensitivityCVarFixed("m_sensitivity_x",   2.5);
        fixed y_sensitivity        = GetOddSensitivityCVarFixed("m_sensitivity_y",   5.0);
        fixed total_sensitivity    = max(x_sensitivity, y_sensitivity) * mouse_sensitivity;
        
        xScale = GetCVarFixed("m_yaw")   * total_sensitivity;
        yScale = GetCVarFixed("m_pitch") * total_sensitivity;
        // kd: aight now back to Ryan coding
        
        // vBuffer = PDA_LocalMouse.y - PDA_LocalMouse.oldY;

        handleMouseMove(inverted, xScale, yScale, PDA_X_sensitivity, PDA_Y_sensitivity);

        handleScroll(yScale);

        handleClicks();

        localCursor = handleCursorChange();

        DisplayIconAlways(localCursor, PDA_CURSORID, PDA_LocalMouse.x + 0.1, PDA_LocalMouse.y + 0.1, 0, (PDA_LocalMouse.m1) ? 0.8 : 1);

        Delay(1);
        PDA_Local.prevScrollingY = PDA_Local.scrollingY;
        PDA_LocalMouse.moving = false;
        PDA_LocalMouse.oldX = PDA_LocalMouse.x;
        PDA_LocalMouse.oldy = PDA_LocalMouse.y;

        // vBuffer = 0;
    }
}

// EOF
