// All on-creation/switch calls should be handled here to avoid constant data thrashing

switch (PDA_Local.category) {
  case PDA_MENU:
    PDA_LocalButton[PDA_PLAYERS_BUTTON]    = PDA_CreateMenuButton(PDA_PLAYERS_BUTTON,    "", "MPLYICO", 10.0, 20.0 + (20.0 * 0), PDA_MENU_BTN_W, PDA_MENU_BTN_H);
    PDA_LocalButton[PDA_WEAPONS_BUTTON]    = PDA_CreateMenuButton(PDA_WEAPONS_BUTTON,    "", "MWEPICO", 10.0, 20.0 + (20.0 * 1), PDA_MENU_BTN_W, PDA_MENU_BTN_H);
    PDA_LocalButton[PDA_ARMORS_BUTTON]     = PDA_CreateMenuButton(PDA_ARMORS_BUTTON,     "", "MARMICO", 10.0, 20.0 + (20.0 * 2), PDA_MENU_BTN_W, PDA_MENU_BTN_H);
    PDA_LocalButton[PDA_ASSEMBLIES_BUTTON] = PDA_CreateMenuButton(PDA_ASSEMBLIES_BUTTON, "", "MASMICO", 10.0, 20.0 + (20.0 * 3), PDA_MENU_BTN_W, PDA_MENU_BTN_H);
    PDA_LocalButton[PDA_ITEMS_BUTTON]      = PDA_CreateMenuButton(PDA_ITEMS_BUTTON,      "", "MITMICO", 10.0, 20.0 + (20.0 * 4), PDA_MENU_BTN_W, PDA_MENU_BTN_H);
    PDA_LocalButton[PDA_BESTIARY_BUTTON]   = PDA_CreateMenuButton(PDA_BESTIARY_BUTTON,   "", "MBESICO", 10.0, 20.0 + (20.0 * 5), PDA_MENU_BTN_W, PDA_MENU_BTN_H);
    PDA_LocalButton[PDA_MISC_BUTTON]       = PDA_CreateMenuButton(PDA_MISC_BUTTON,       "", "MMSCICO", 10.0, 20.0 + (20.0 * 6), PDA_MENU_BTN_W, PDA_MENU_BTN_H);
    PDA_LocalButton[PDA_HELP_BUTTON]       = PDA_CreateMenuButton(PDA_HELP_BUTTON,       "", "MHLPICO", 10.0, 20.0 + (20.0 * 7), PDA_MENU_BTN_W, PDA_MENU_BTN_H);
    PDA_LocalButton[PDA_WINFO_BUTTON]      = PDA_CreateMenuButton(PDA_WINFO_BUTTON,      "", "MHLPICO", 10.0, 20.0 + (20.0 * 7), PDA_MENU_BTN_W, PDA_MENU_BTN_H);
    break;

  case PDA_CLASSES:
    PDA_LocalButton[PDA_TAB_BUTTONS_START    ] = PDA_CreateTab(PDA_TAB_BUTTONS_START    , "1", "PTAB", PDA_TAB_START_X  , PDA_TAB_Y,  PDA_TAB_W, PDA_TAB_H);
    PDA_LocalButton[PDA_TAB_BUTTONS_START + 1] = PDA_CreateTab(PDA_TAB_BUTTONS_START + 1, "2", "PTAB", PDA_TAB_NEXT_X(1), PDA_TAB_Y,  PDA_TAB_W, PDA_TAB_H);

    if (GetActorClass(0) != "None")
    {
        if (stricmp(PDA_Class[PlayerNumber()][pda_class_icon], "PDA_", 4) == 0) {
          PDA_Class[PlayerNumber()][pda_class_icon] = "PPDAUNK";
        }
          
        SetFont(PDA_Class[PlayerNumber()][pda_class_icon]);
        HudMessage(s:"A\n"; HUDMSG_ALPHA, PDA_INFOID, CR_UNTRANSLATED,  PDA_SCREEN_WIDTH + 5.0 + X_RIGHT_EDGE, (PDA_SCROLLABLE_HEIGHT) + 5.0 + Y_TOP_EDGE, 0, 0.45);
        
        PDA_DefaultFont();
        // Class perks
        if (PDA_Local.page == CLASSES_PAGE_PERKS)
        {
            PDA_HudDirtyP(HUDMSG_PLAIN, PDA_INFO2ID, CR_UNTRANSLATED, 10.0, 20.0 + (20.0 * 1), INF_HOLDTIME, OPAQUE,
              s:"\cd",
              l:PDA_Class[PlayerNumber()][pda_class_name],
              s:"\c-\n\n",
              l:PDA_Class[PlayerNumber()][pda_class_abilities]
            );
        }
        // Class backstory
        if (PDA_Local.page == CLASSES_PAGE_STORY)
        {
            PDA_HudDirtyP(HUDMSG_PLAIN, PDA_INFO2ID, CR_UNTRANSLATED, 10.0, 20.0 + (20.0 * 1), INF_HOLDTIME, OPAQUE,
              s:"\cd",
              l:PDA_Class[PlayerNumber()][pda_class_name],
              s:"\c-\n\n",
              l:PDA_Class[PlayerNumber()][pda_class_story]
            );
        }
    }
    break;

  case PDA_WEAPONS:
    PDA_LocalButton[PDA_TAB_BUTTONS_START    ] = PDA_CreateTab(PDA_TAB_BUTTONS_START    , "1", "PTAB", PDA_TAB_START_X  , PDA_TAB_Y,  PDA_TAB_W, PDA_TAB_H);
    PDA_LocalButton[PDA_TAB_BUTTONS_START + 1] = PDA_CreateTab(PDA_TAB_BUTTONS_START + 1, "2", "PTAB", PDA_TAB_NEXT_X(1), PDA_TAB_Y,  PDA_TAB_W, PDA_TAB_H);
    PDA_LocalButton[PDA_TAB_BUTTONS_START + 2] = PDA_CreateTab(PDA_TAB_BUTTONS_START + 2, "3", "PTAB", PDA_TAB_NEXT_X(2), PDA_TAB_Y,  PDA_TAB_W, PDA_TAB_H);

    PDA_DefaultFont();

    if (stricmp(player_weapon[player_weapon_current], "None") != 0) {
        if (PDA_Local.page == WEAPON_PAGE_STORY) {
            #include "../../pages/subpage/weapons_story_draw.pdap"
        }

        if (PDA_Local.page == WEAPON_PAGE_MODPACK_EFFECTS) {
            #include "../../pages/subpage/weapons_mods_draw.pdap"
            
        }
        if (PDA_Local.page == WEAPON_PAGE_ARTIFACT_EFFECTS) {
            #include "../../pages/subpage/weapons_artifacts_draw.pdap"
        }
    }
    break;

  case PDA_BESTIARY:
    PDA_LocalButton[PDA_BEAST_UV] = PDA_CreateBeastButton(PDA_BEAST_UV, "Normal",       CR_WHITE,     10.0, 30.0 + (15.0 * 0), BEAST_DIFFICULTY_WIDTH, BEAST_DIFFICULTY_HEIGHT, -4.0, -3.0, "", "");
    PDA_LocalButton[PDA_BEAST_NM] = PDA_CreateBeastButton(PDA_BEAST_NM, "Nightmare",    CR_BRICK,     10.0, 30.0 + (15.0 * 1), BEAST_DIFFICULTY_WIDTH, BEAST_DIFFICULTY_HEIGHT, -4.0, -3.0, "" , "");
    PDA_LocalButton[PDA_BEAST_TP] = PDA_CreateBeastButton(PDA_BEAST_TP, "Technophobia", CR_LIGHTBLUE, 10.0, 30.0 + (15.0 * 2), BEAST_DIFFICULTY_WIDTH, BEAST_DIFFICULTY_HEIGHT, -4.0, -3.0, "", "");
    PDA_LocalButton[PDA_BEAST_AG] = PDA_CreateBeastButton(PDA_BEAST_AG, "Armageddon",   CR_GOLD,      10.0, 30.0 + (15.0 * 3), BEAST_DIFFICULTY_WIDTH, BEAST_DIFFICULTY_HEIGHT, -4.0, -3.0, "", "");
    PDA_LocalButton[PDA_BEAST_EX] = PDA_CreateBeastButton(PDA_BEAST_EX, "Extra",        CR_PURPLE,    10.0, 30.0 + (15.0 * 4), BEAST_DIFFICULTY_WIDTH, BEAST_DIFFICULTY_HEIGHT, -4.0, -3.0, "", "");

    beast_info[0] = PDA_Local.page - 2;

    if (PDA_Local.page != BESTIARY_PAGE_DIFFICULTIES) {
      for (int i = 0; i < DRLA_MONSTER_PAGE_MAX; i++) {
        localListEnemy[list_kill_count] = StrParam("%s:KillCounter", DRLA_Bestiary[beast_info[0]][i][beast_TOKEN]);
        monsterCheck[beast_info[0]][i]  = CheckInventory(localListEnemy[list_kill_count]);

        fixed beast_y = 30.0 + (16.0 * i);
        
        if (CheckInventory(localListEnemy[list_kill_count]) > 0)
        {
            localListEnemy[list_actor] = DRLA_Bestiary[beast_info[0]][i][beast_ACTOR];
            localListEnemy[list_name]  = StrParam("%l:", StrParam("%l:_name", localListEnemy[list_actor]));
            localListEnemy[list_icon]  = StrParam("%l:", StrParam("%l:_icon", localListEnemy[list_actor]));
            player_kill_count          = CheckPointerInventory(localListEnemy[list_kill_count], PlayerNumber());
            beast_info[1]              = (StrLen(localListEnemy[list_name]) * 10) / 2;
        } else {
            localListEnemy[list_actor] = "null";
            player_kill_count          = 0;
            localListEnemy[list_name]  = " ????";
        }

        const int buttonID = PDA_BEASTS_ID_END - i;

        PDA_LocalButton[buttonID] = PDA_CreateBeastButton(buttonID, localListEnemy[list_name], beast_info[2], 
            beast_x, beast_y, 
            beast_info[1], 10, 
            3.0, -3.0, 
            localListEnemy[list_actor], player_kill_count);

        if (localListEnemy[list_name] != " ????") {
            if (PDA_LocalButton[buttonID].state == button_hovered) {
                if (CheckFont(localListEnemy[list_icon])) {
                    DisplayIcon(localListEnemy[list_icon], PDA_INFO2ID, PDA_SCREEN_WIDTH - 30.0 + X_LEFT_EDGE, PDA_SCREEN_Y + 100.0 + Y_TOP_EDGE, 0, 0.2 + pulser(2.0, 0.59));
                } else {
                    DisplayIcon("EPDAUNK", PDA_INFO2ID, PDA_SCREEN_WIDTH - 30.0 + X_LEFT_EDGE, PDA_SCREEN_Y + 100.0 + Y_TOP_EDGE, 0, 0.2 + pulser(2.0, 0.59));
                }
            }
        }
      }
    }

    break;

  case PDA_BESTIARY_DETAIL:
    #define LocalEnemy PDA_Enemy[PlayerNumber()]
    if (!PDA_Local.playSoundOnce) {
        PDA_PlaySound("UI/PDA/Activate", "pda/soldier", 80);

        PDA_Local.playSoundOnce = true;
    }

      SetFont(PDA_FONT[mono_font]);
    if (StrCmp(PDA_Local.detailFetch[0], "null") != 0) {
        // Monster icon
        DisplayIcon(StrParam("%l:", LocalEnemy[enemy_icon]), PDA_INFO2ID, PDA_SCREEN_WIDTH - 50.0 + X_LEFT_EDGE, PDA_Local.scrollingY + 110.0 + Y_TOP_EDGE, 0, 0.8);

        PDA_HudDirtyP(HUDMSG_PLAIN, PDA_INFO3ID, CR_UNTRANSLATED, 5.0, 20.0 + (20.0 * 1), INF_HOLDTIME, OPAQUE,
          s:"\cdName:\c- ",l:LocalEnemy[enemy_name],s:"\n",
          s:"\cdNo. of Kills:\c- ",i:enemy_count,s:"\n",
          s:"\cdHealth:\c- ",l:LocalEnemy[enemy_health],s:"\n",
          s:"\cdResistances:\c- \n",l:LocalEnemy[enemy_resistance],s:"\n",
          s:"\cdDrops and misc info:\c- \n",l:LocalEnemy[enemy_misc],s:"\n"
        );
    } else {
        PDA_HudDirtyP(HUDMSG_PLAIN, PDA_INFO3ID, CR_UNTRANSLATED, 5.0, 20.0 + (20.0 * 1), INF_HOLDTIME, OPAQUE,
          l:"PDA_BESTIARY_DEFAULT_NAME",s:"\n",
          l:"PDA_BESTIARY_DEFAULT_KILLS",s:"\n",
          l:"PDA_BESTIARY_DEFAULT_HEALTH",s:"\n",
          l:"PDA_BESTIARY_DEFAULT_RESISTANCES",s:"\n",
          l:"PDA_BESTIARY_DEFAULT_DESC",s:"\n"
        );
    }
    break;
    
  case PDA_ARMORS:
    const fixed playerIconX = PDA_SCREEN_X + 20.0 + X_LEFT_EDGE;
    bool specialArmorTokens = checkSpecialArmorTokens();
    localArmorData          = setupArmorData(specialArmorTokens);
    localBootsData          = setupBootsData();
    localBackpackData       = setupBackpackData();

    PDA_LocalButton[PDA_TAB_BUTTONS_START    ] = PDA_CreateTab(PDA_TAB_BUTTONS_START    , "1", "PTAB", PDA_TAB_START_X  , PDA_TAB_Y,  PDA_TAB_W, PDA_TAB_H);
    PDA_LocalButton[PDA_TAB_BUTTONS_START + 1] = PDA_CreateTab(PDA_TAB_BUTTONS_START + 1, "2", "PTAB", PDA_TAB_NEXT_X(1), PDA_TAB_Y,  PDA_TAB_W, PDA_TAB_H);

    PDA_LocalButton[PDA_PLAYER_ARMOR_ICON]    = PDA_DisplayArmor(PDA_PLAYER_ARMOR_ICON   , ARMOR_DATA   , playerIconX + 35.0, 20.0, 16, localShowArmor    ? pulser(2.0, 0.8) : 0.7),
    PDA_LocalButton[PDA_PLAYER_BACKPACK_ICON] = PDA_DisplayArmor(PDA_PLAYER_BACKPACK_ICON, BACKPACK_DATA, playerIconX + 33.0, 45.0, 16, localShowBackpack ? pulser(2.0, 0.8) : 0.7),
    PDA_LocalButton[PDA_PLAYER_BOOTS_ICON]    = PDA_DisplayArmor(PDA_PLAYER_BOOTS_ICON   , BOOTS_DATA   , playerIconX + 30.0, 70.0, 16, localShowBoots    ? pulser(2.0, 0.8) : 0.7);

    // bool specialArmorTokens = checkSpecialArmorTokens();
    #define ARM_X 10.0
    #define ARM_GAP 4
    #define isRenegade (CheckActorClass(0, CheckInventory("DRPGDRLAActive") ? "DoomRLRenegadeRPG" : "DoomRLRenegade") == true)

    fixed armorY = PDA_Local.equipmentBaseY;
    PDA_Local.equipmentId = 0;
    PDA_Local.stopEquipmentEarly = false;

    // Note to future self: don't try to merge these first 5 lines for cleanliness sake. Won't work the way you wish it would.
    if (localHasArmor) {
        PDA_Local.equipmentId = (PDA_WORNARMORS - 4) + (PDA_Local.equipmentLimit * 4);
        if (PDA_Local.equipmentLimit > PDA_MAX_ARMOR_IN_INV + 1) PDA_Local.equipmentLimit = 0;
        else PDA_Local.equipmentLimit++;
        armorY += ARM_HEIGHT + ARM_GAP;
    }

    if (localHasBoots) {
        PDA_Local.equipmentId = (PDA_WORNARMORS - 4) + (PDA_Local.equipmentLimit * 4);
        if (PDA_Local.equipmentLimit > PDA_MAX_ARMOR_IN_INV + 1) PDA_Local.equipmentLimit = 0;
        else PDA_Local.equipmentLimit++;
        armorY += ARM_HEIGHT + ARM_GAP;
    }
    
    str armorPickupCheck = "\n";
    
    for (int armorIndex = 0; armorIndex < DRLA_ARMORMAX; armorIndex++) {
        #define _armorToken DRLA_ArmorList[armorIndex][armor_TOKEN]
        #define _armorActor DRLA_ArmorList[armorIndex][armor_ACTOR]

        armorPickupCheck = StrParam("%s:Pickup", _armorToken);

        if (PDA_Local.stopEquipmentEarly) break;

        if (CheckInventory(armorPickupCheck)) {
            PDA_Local.equipmentId = (PDA_STASHEDARMORS - 8) + (PDA_Local.equipmentLimit * 2);
            if (PDA_Local.equipmentLimit > PDA_MAX_ARMOR_IN_INV + 1) PDA_Local.equipmentLimit = 0;
            else PDA_Local.equipmentLimit++;
            armorY += ARM_HEIGHT + ARM_GAP;

            str protKey = (!isRenegade) ? StrParam("%l:_PROT", localArmorData.langEntry) 
                                        : StrParam("%l:_RENPROT", localArmorData.langEntry);
            
            if (StrCmp(_armorToken, StrParam("%s:Boots", StrTrim(_armorToken,0,5))) != 0) {
                localArmorData.langEntry = StrParam("PDA_ARMOR_%s:", _armorActor);
                localArmorData.name      = StrParam("%l:", StrParam("%l:_NAME", localArmorData.langEntry));
                localArmorData.graphic   = StrParam("%l:", StrParam("%l:_ICON", localArmorData.langEntry));
                localArmorData.armorAttr = StrParam("%l:", StrParam("%l:_ATTR", localArmorData.langEntry));
                localArmorData.tooltip   = StrParam(
                    "\cdStats:\c-\n"
                    "%l:\n" // 1*
                    "%l:\n" // 2*
                    "%l:", // 3*
                    protKey,
                    StrParam("%l:_RES", localArmorData.langEntry),  // 2
                    localArmorData.armorAttr // 3
                );
            } else {
                localBootsData.langEntry = StrParam("PDA_ARMOR_%s:", _armorActor);
                localBootsData.name      = StrParam("%l:", StrParam("%l:_NAME", localBootsData.langEntry));
                localBootsData.graphic   = StrParam("%l:", StrParam("%l:_ICON", localBootsData.langEntry));
                localBootsData.bootsAttr = StrParam("%l:", StrParam("%l:_ATTR", localBootsData.langEntry));
                localBootsData.tooltip   = StrParam(
                    "\cdStats:\c-\n"
                    "%l:\n\n" // 1*
                    "%l:", // 2*
                    StrParam("%l:_PROT", localBootsData.langEntry), // 1
                    localBootsData.bootsAttr // 2
                );
            }
        }
    }

    if (PDA_Local.page == EQUIPMENT_PAGE_ONHAND) {
        #include "../../pages/subpage/armors_onhand_draw.pdap"
    }

    // Detailed information on currently equipped gear (armor, boots, backpack)
    if (PDA_Local.page == EQUIPMENT_PAGE_INFO) {
        #include "../../pages/subpage/armors_detail_draw.pdap"
    }
    break;

  case PDA_ARMOR_DETAIL:
    // Clicked-on equipment info
    bool PDA_ManyHax  = false;

    int equipmentType = 0;
    if (PDA_Local.detailFetch[0] == "armor") equipmentType = EQUIPMENT_TYPE_ARMOR;
    if (PDA_Local.detailFetch[0] == "boots") equipmentType = EQUIPMENT_TYPE_BOOTS;

    str equipment_set_name        = "N/A\n",
        equipment_set_description = "\n\n";

    // Armor
    for (int setIndex = 0; setIndex < DRLA_ARMORSETMAX; setIndex++) {
        if (CheckInventory(DRLA_ArmorSetList[setIndex])) {
            if (CheckInventory("RLEnclaveSetBonusActive") && CheckInventory("RLNuclearWeaponSetBonusActive")) {}
                PDA_ManyHax = true;
            }

            #define trimmedList strTrim(DRLA_ArmorSetList[setIndex],2,0)

            equipment_set_name = StrParam("%l:\n\n", (PDA_ManyHax)
                ? "PDA_ARMOR_NuclearWeaponSetBonusActive_equipment_set_name"
                : StrParam("PDA_ARMOR_%s:_equipment_set_name", trimmedList));
            equipment_set_description = StrParam("%l:\n\n", (PDA_ManyHax)
                ? "PDA_ARMOR_NuclearWeaponSetBonusActive_equipment_set_description"
                : StrParam("PDA_ARMOR_%s:_equipment_set_description", trimmedList));
        }
    }


    switch (equipmentType) {
        case EQUIPMENT_TYPE_ARMOR:
          SetFont(PDA_FONT[mono_font]);
          DisplayIconParallax(localArmorData.graphic, PDA_PLAYER_ARMOR_ICON, EQUIPMENT_ICON_X, EQUIPMENT_ICON_Y, INF_HOLDTIME, OPAQUE);

          PDA_HudDirtyP(HUDMSG_PLAIN, PDA_INFOID, CR_UNTRANSLATED, 10.0, EQUIPMENT_TEXT_Y, INF_HOLDTIME, OPAQUE,
            s:"\cgARMOR\c-\n",
            s:"\crProtection:\c-\n",l:localArmorData.armorVal,
            s:"\crResistances:\c-\n",l:localArmorData.armorRes,s:"\n",
            s:"\crAttributes:\c-\n",l:localArmorData.armorAttr,s:"\n\n",
            s:"\crDescription:\c-\n",l:localArmorData.armorDesc,s:"\n\n",
            s:"\crSet bonus:\c-\n",
            l:(PDA_ManyHax) ? StrParam("%l:\n\n", "PDA_ARMOR_EnclaveSetBonusActive_equipment_set_name") : "",s:" ",l:(PDA_ManyHax) ? StrParam("%l:\n\n", "PDA_ARMOR_EnclaveSetBonusActive_equipment_set_description") : "",
            l:equipment_set_name,s:" ",l:equipment_set_description
          );
          break;
        case EQUIPMENT_TYPE_BOOTS:
          SetFont(PDA_FONT[mono_font]);
          DisplayIconParallax(localBootsData.graphic, PDA_PLAYER_BOOTS_ICON, EQUIPMENT_ICON_X, EQUIPMENT_ICON_Y, INF_HOLDTIME, OPAQUE);

          PDA_HudDirtyP(HUDMSG_PLAIN, PDA_INFO2ID, CR_UNTRANSLATED, 10.0, EQUIPMENT_TEXT_Y, INF_HOLDTIME, OPAQUE,
            s:"\cgBOOTS\c-\n",
            s:"\crProtection:\c-\n",l:localBootsData.bootsVal,
            s:"\crAttributes:\c-\n",l:localBootsData.bootsAttr,s:"\n",
            s:"\crDescription:\c-\n",l:localBootsData.bootsDesc,s:"\n"
          );
          break;
        default:
          Log("ERR: Invalid equipment type");
          break;
    }

    if (localHasBackpack) {
        SetFont(PDA_FONT[mono_font]);

        PDA_HudDirtyP(HUDMSG_PLAIN, PDA_INFO3ID, CR_UNTRANSLATED, 10.0, 40.0, INF_HOLDTIME, OPAQUE,
          s:"\cgBACKPACK\c-\n",
          s:"\crDescription:\c-\n",
          l:localBackpackData.backpackVal
        );
    }

    break;

  case PDA_ASSEMBLIES:
    float paginationY = 35.0 + (6.0 * PDA_Local.maxAssembliesPer);

    float nextButtonX = 10.0;
    if (PDA_Local.page > 1 && PDA_Local.page < 3) {
      nextButtonX = PDA_SCREEN_WIDTH + PDA_SCREEN_X - 82;
    }

    PDA_LocalButton[PDA_TAB_BUTTONS_START    ] = PDA_CreateTab(PDA_TAB_BUTTONS_START    , "1", "PTAB", PDA_TAB_START_X  , PDA_TAB_Y, PDA_TAB_W, PDA_TAB_H);
    PDA_LocalButton[PDA_TAB_BUTTONS_START + 1] = PDA_CreateTab(PDA_TAB_BUTTONS_START + 1, "2", "PTAB", PDA_TAB_NEXT_X(1), PDA_TAB_Y, PDA_TAB_W, PDA_TAB_H);
    PDA_LocalButton[PDA_TAB_BUTTONS_START + 2] = PDA_CreateTab(PDA_TAB_BUTTONS_START + 2, "3", "PTAB", PDA_TAB_NEXT_X(2), PDA_TAB_Y, PDA_TAB_W, PDA_TAB_H);
    
    PDA_LocalButton[PDA_PREV_PAGE] = PDA_CreateButton(PDA_PREV_PAGE, "Previous tier", "A_PREV",        10.0, paginationY, 82, 16, 20, 15);
    PDA_LocalButton[PDA_NEXT_PAGE] = PDA_CreateButton(PDA_NEXT_PAGE, "Next tier"    , "A_NEXT", nextButtonX, paginationY, 82, 16, 20, 15);

    float assemblyX = 20.0,
          assemblyY;
    const int width = 180, 
              height = 7;

    for (int ti = 0, li = 1; ti <= PDA_Local.maxAssembliesPer; ti+=2, li+=2) {
        int aoff               = (PDA_Local.assemblyOffset - 1 < 0) ? 0 : (PDA_Local.assemblyOffset - 1);
        str actorToken         = stringArray[ASSEMBLY_DIM][ti + aoff];
        str languagePointer    = stringArray[ASSEMBLY_DIM][li + aoff];
        int id                 = PDA_ASSEMBLY_ID_END - (ti - 1); // index - 1 to account for message id
            assemblyY          = 30.0 + (6.0 * (ti - 1)); 
        str icon               = StrParam("%l:",    StrParam("%s:_ICON", languagePointer));
        str colored_label      = StrParam("%s:%l:\c-", PDA_Local.tierColor, languagePointer);
        str callback           = languagePointer;
        str tooltip            = StrParam("%l:\n%l:\n%l:", 
                                    StrParam("%s:%l:\c-", PDA_Local.tierColor, StrParam("%s:_NAME", languagePointer)), 
                                    "PDA_ASSEMBLY_REQUIREMENTS", 
                                    StrParam("%s:_REQ", languagePointer)
                                );

        if (ti + 2 >= advanced_offset && PDA_Local.assemblyOffset < advanced_offset) continue;
        if (ti + 2 >= master_offset   && PDA_Local.assemblyOffset < master_max     ) continue;

        if (!PDA_CheckPlayer1Inventory(actorToken) || !CheckInventory(actorToken)) {
            icon = "PDAUNK";
            colored_label = StrParam(l:"PDA_ASSEMBLY_UNKNOWN");
            callback = "";
            tooltip = "???";
        }
        
        PDA_LocalButton[id] = PDA_CreateAssemblyButton(id, icon, colored_label, assemblyX, assemblyY, width, height, callback, tooltip);
    }

    if (PDA_Local.page > 1) {
        PDA_LocalButton[PDA_PREV_PAGE] = PDA_CreateButton(PDA_PREV_PAGE, "Previous tier" , "A_PREV", 10.0, paginationY, 82, 16, 20, 15);
    }

    if (PDA_Local.page < 3) {
        PDA_LocalButton[PDA_NEXT_PAGE] = PDA_CreateButton(PDA_NEXT_PAGE, "Next tier" , "A_NEXT", nextButtonX, paginationY, 82, 16, 20, 15);
    }


    break;

  case PDA_ASSEMBLY_DETAIL: 
    str detailedAssemblyStringer;

    if (!PDA_Local.playSoundOnce) {
        PDA_PlaySound("UI/PDA/Activate", "pda/soldier", 80);

        PDA_Local.playSoundOnce = true;
    }

    if (StrCmp(PDA_Local.detailFetch[0], "null") != 0) {
        DisplayArmorIcon(PDA_AssemblyInfo[PlayerNumber()][0], PDA_INFOID, PDA_SCREEN_X + 150.0 + X_LEFT_EDGE, PDA_Local.scrollingY + 40.0 + Y_TOP_EDGE + (20.0 * 1), 1);

        PDA_HudDirtyP(HUDMSG_PLAIN, PDA_INFO2ID, CR_WHITE, 10.0, 50.0 + (20.0 * 1), INF_HOLDTIME, OPAQUE,
          l:PDA_AssemblyInfo[PlayerNumber()][1],s:"\n",
          l:PDA_AssemblyInfo[PlayerNumber()][2],s:"\n\n\n",
          l:PDA_AssemblyInfo[PlayerNumber()][3],s:"\n"
        );
            
        if (StrCmp(StrParam("%l:", PDA_AssemblyInfo[PlayerNumber()][4]), PDA_AssemblyInfo[PlayerNumber()][4]) != 0) {
            PDA_SetScrollLimit(-1 * batoi(StrParam("%l:", PDA_AssemblyInfo[PlayerNumber()][4])));
            PDA_SetScrollArrows2(-1 * batoi(StrParam("%l:", PDA_AssemblyInfo[PlayerNumber()][4])), PDA_SCREEN_WIDTH + 60.0, PDA_SCROLLABLE_HEIGHT + 90.0);
        }
    } else {
        PDA_HudDirtyP(HUDMSG_PLAIN, PDA_INFO2ID, CR_WHITE, 10.0, 50.0 + (20.0 * 1), INF_HOLDTIME, OPAQUE,
          l:"PDA_ASSEMBLY_NOTFOUND_NAME",s:"\n",
          l:"PDA_ASSEMBLY_NOTFOUND_MODS",s:"\n\n\n",
          l:"PDA_ASSEMBLY_NOTFOUND_DESC",s:"\n"
        );
    }
    break;

  case PDA_CREDITS:
    SetFont(PDA_FONT[lower_font]);
    PDA_HudDirtyP(HUDMSG_PLAIN, PDA_INFO2ID, CR_WHITE, 10.0, 50.0 + (20.0 * 1), INF_HOLDTIME, OPAQUE,
      l:"PDA_ASSEMBLY_NOTFOUND_NAME",s:"\n",
      l:"PDA_ASSEMBLY_NOTFOUND_MODS",s:"\n\n\n",
      l:"PDA_ASSEMBLY_NOTFOUND_DESC",s:"\n"
    );
    HudMessage("%l:", "PDA_DEV_TEAM"; HUDMSG_PLAIN, PDA_INFOID, CR_UNTRANSLATED, (PDA_SCREEN_X) + 120.0 + X_CENTER_TEXT_CENTER, (int)PDA_Local.creditsroll + PDA_NormalY + 20.0 + Y_TOP_EDGE + (10.0 * 1), 0);
    break;

  case PDA_HELP:
    PDA_LocalButton[PDA_TAB_BUTTONS_START    ] = PDA_CreateTab(PDA_TAB_BUTTONS_START    , "1", "PTAB", PDA_TAB_START_X  , PDA_TAB_Y,  PDA_TAB_W, PDA_TAB_H);
    PDA_LocalButton[PDA_TAB_BUTTONS_START + 1] = PDA_CreateTab(PDA_TAB_BUTTONS_START + 1, "2", "PTAB", PDA_TAB_NEXT_X(1), PDA_TAB_Y,  PDA_TAB_W, PDA_TAB_H);

    if (PDA_Local.page == 1) {
      PDA_HudDirtyP(HUDMSG_PLAIN, PDA_INFOID, CR_UNTRANSLATED, 10.0, 20.0 + (20.0 * 1), INF_HOLDTIME, OPAQUE,
          l:(GetUserCvar(PlayerNumber(), "DRLA_PDA_firsttime") ? "PDA_PDAHELP_FIRSTTIME" : "PDA_BLANK"),s:"\n",
          l:"PDA_PDAHELP_CONTROLS",s:"\n",
          s:"(\cd",k:"+attack",s:" / ",k:"+use",s:"\c-) \n",
          s:"\n",
          l:"PDA_PDAHELP_MOUSE1",s:"\n",
          s:"(\cd",k:"+altattack",s:" / ",k:"+jump",s:"\c-) \n",
          l:"PDA_PDAHELP_MOUSE2",
          s:"\n\cgIf mouse look is disabled..\c-\n",
          s:"(\cd", k:"+forward",s:" / ",k:"+back",s:"\c-) ",
          l:"PDA_PDAHELP_YAXIS",
          s:"\n",
          s:"(\cd",k:"+moveleft",s:" / ",k:"+moveright",s:"\c-) ",
          l:"PDA_PDAHELP_XAXIS",
          s:"\n"
      );
    }
    if (PDA_Local.page == 2) {
      PDA_HudDirtyP(HUDMSG_PLAIN, PDA_INFOID, CR_UNTRANSLATED, 10.0, 20.0 + (20.0 * 1), INF_HOLDTIME, OPAQUE,
          s:"\cd(",k:"invuse",s:"\c-, \cd",k:"+zoom",s:")\c- ",
          l:"PDA_DRLAHELP_DROPITEM",
          s:"\cd(",k:"+use",s:")\c- ",
          l:"PDA_DRLAHELP_BACKPACK",
          l:"PDA_DRLAHELP_CRATE"
      );
    }
    if (PDA_Local.page == 3) {
      PDA_HudDirtyP(HUDMSG_PLAIN, PDA_INFOID, CR_UNTRANSLATED, 10.0, 20.0 + (20.0 * 1), INF_HOLDTIME, OPAQUE,
          s:"\cc",l:"PDA_DRLAHELP_DMG",s:"\c-"
      );
    }
    break;

  case PDA_WINFO:
    PDA_HudDirtyP(HUDMSG_PLAIN, PDA_INFOID, CR_UNTRANSLATED, 10.0, 20.0 + (20.0 * 1), INF_HOLDTIME, OPAQUE,
    s:"Damage formulas explained:\n",
    s:"(XdN) = Random value of 1 to X multiplied by N.\n",
    s:"(X~Y) = Random value between X and Y. Used when the minimum value X is not 1, and thus cannot\nbe represented with the above formula.\n",
    s:"((X~Y)*N) = Effectively a combination of the two formulas above.\n",
    s:"<X> = Splash damage of X value.\n",
    s:"<X...Y> = Splash damage of minimum X value, all the way up to Y.\n",
    s:"(X) = Non-random damage value.\n",
    s:"(X)! = Non-random damage value on a Ripper projectile.\n",
    s:"(X) - N = X damage value with N subtracted from the final result.\n",
    s:"Y x (N) = Y amount of bullets dealing N damage.\n",
    s:"Y? x (N) = Y amount of bullets dealing N damage with dual wielded weapons.\n");
    break;

  case PDA_MISC:
    PDA_LocalButton[49] =   PDA_CreateButton(49, "Credits", "PLON",      PDA_SCREEN_X + 10.0 + X_LEFT_EDGE, 30.0 + Y_TOP_EDGE + (14.0 * 1), 32, 8, -3.0 + X_LEFT_EDGE, 0);
                          // PDA_InitButton(CREDITS, false, PDA_CREDITS,    "All the wonderful people that helped bring this together.\n", false);

    PDA_LocalButton[50] = PDA_CreateButton(50, "HUD Switcher", "PLON", PDA_SCREEN_X + 10.0 + X_LEFT_EDGE, 30.0 + Y_TOP_EDGE + (14.0 * 2), 32, 8, -3.0 + X_LEFT_EDGE, 0);
                          // PDA_InitButton(HUDSWITCH, false, PDA_HUDSWITCH,    "Select which HUD you would like to use\n", false);

    //PDAButton PONG    = PDA_CreateButton(51, "Pong",    "PLON", PDA_SCREEN_X + 10.0 + X_LEFT_EDGE, 30.0 + Y_TOP_EDGE + (14.0 * 0), 32, 8, -3.0 + X_LEFT_EDGE, 0);
    //PDA_InitButton(PONG,    false, PDA_PONG,       "Play Pong! (Temporarily SP only)\n");

    //PDAButton JUKEBOX = PDA_CreateButton(50, "Jukebox", "TNT1A0", PDA_SCREEN_X + 10.0 + X_LEFT_EDGE, 30.0 + Y_TOP_EDGE + (14.0 * 2), 32, 12);
    //PDA_InitButton(JUKEBOX, false, PDA_CLASSES,    "Play random music\n");

    //PDAButton EMAIL   = PDA_CreateButton(53, "Email",   "TNT1A0", PDA_SCREEN_X + 10.0 + X_LEFT_EDGE, 30.0 + Y_TOP_EDGE + (14.0 * 3), 32, 12);
    //PDA_InitButton(EMAIL,   false, PDA_ASSEMBLIES, "Read up emails\n");
    break;


  case PDA_ITEMS:
    PDA_LocalButton[PDA_TAB_BUTTONS_START    ] = PDA_CreateTab(PDA_TAB_BUTTONS_START    , "1" , "PTAB", PDA_TAB_START_X  , PDA_TAB_Y,  PDA_TAB_W, PDA_TAB_H);
    PDA_LocalButton[PDA_TAB_BUTTONS_START + 1] = PDA_CreateTab(PDA_TAB_BUTTONS_START + 1, "2" , "PTAB", PDA_TAB_NEXT_X(1), PDA_TAB_Y,  PDA_TAB_W, PDA_TAB_H);
    PDA_LocalButton[PDA_TAB_BUTTONS_START + 2] = PDA_CreateTab(PDA_TAB_BUTTONS_START + 2, "3" , "PTAB", PDA_TAB_NEXT_X(2), PDA_TAB_Y,  PDA_TAB_W, PDA_TAB_H);
    PDA_LocalButton[PDA_TAB_BUTTONS_START + 3] = PDA_CreateTab(PDA_TAB_BUTTONS_START + 3, "4" , "PTAB", PDA_TAB_NEXT_X(3), PDA_TAB_Y,  PDA_TAB_W, PDA_TAB_H);
    PDA_LocalButton[PDA_TAB_BUTTONS_START + 4] = PDA_CreateTab(PDA_TAB_BUTTONS_START + 4, "5" , "PTAB", PDA_TAB_NEXT_X(4), PDA_TAB_Y,  PDA_TAB_W, PDA_TAB_H);
    break;
}

// EOF